#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -theme $HOME/.cache/wal/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="󰠻"
reboot="󰜉"
lock=""
logout="󱋟"

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        sleep 0.3; sh $HOME/.cache/wal/lock.sh
        ;;
    $logout)
        bspc quit
        ;;
esac
