#!/usr/bin/env sh

setxkbmap us # avoid issues with numbers bindings
pkill sxhkd; sxhkd &
setxkbmap fr

nitrogen --restore
pkill dunst; dunst -conf ~/.cache/wal/dunstrc &
$HOME/.config/polybar/launch
numlockx on

# no compositor on toad
if [[ $HOSTNAME != 'toad' ]]; then
  pkill compton; compton -b --blur-method kawase --blur-strength 8
fi

# colors
source ~/.cache/wal/colors.sh

bspc config active_border_color   $background
bspc config normal_border_color   $background
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color4

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio               0.3
bspc config gapless_monocle           true
bspc config single_monocle            true
bspc config focus_follows_pointer     true
bspc config remove_unplugged_monitors true

bspc rule -a qt5ct state=floating
bspc rule -a feh state=floating
bspc rule -a Vivaldi-stable desktop=2
bspc rule -a ParaView state=floating
bspc rule -a yakyak desktop=4
bspc rule -a mpv desktop=6
bspc rule -a discord desktop=4
bspc rule -a Steam desktop=5
bspc rule -a Peek state=floating
bspc rule -a Vtk state=floating
bspc rule -a vtk state=floating
bspc rule -a CCTEGViewer state=floating
bspc rule -a qapitrace state=floating
bspc rule -a Designer state=floating
bspc rule -a nv-nsight-gfx.bin state=floating

startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  # auto start
  if [[ $HOSTNAME == 'bowser' ]]; then
    bspc monitor -d Desktop 1 2 4 5
    vivaldi-stable&
    steam-runtime&
  fi
  if [[ $HOSTNAME == 'peach' ]]; then
    bspc monitor -d Desktop 1 2 3 3 4
    vivaldi-stable&
    yakyak&
  fi
  if [[ $HOSTNAME == 'toad' ]]; then
    bspc monitor -d Desktop 2 6
    firefox&
  fi
fi

