#! /bin/sh

nitrogen --restore
pkill compton; compton -b --blur-method kawase --blur-strength 8
pkill dunst; dunst -conf ~/.cache/wal/dunstrc &
$HOME/.config/polybar/launch.sh
numlockx on
setxkbmap fr

sxhkd &

bspc monitor -d I II III IV V VI

# colors
source ~/.cache/wal/colors.sh

bspc config active_border_color   $color8
bspc config normal_border_color   $color0
bspc config focused_border_color  $color4
bspc config presel_feedback_color $color3

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc rule -a qt5ct state=floating
bspc rule -a feh state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
