#!/usr/bin/env bash
background={background.strip}ff
foreground={foreground.strip}ff
highlight={color4.strip}ff
error={color1.strip}ff

pkill -u "$USER" -USR1 dunst

i3lock --nofork --blur=10 --clock --indicator --line-uses-inside \
       --insidecolor="$background" --ringcolor="$foreground" \
       --keyhlcolor="$error" --bshlcolor="$error" \
       --insidevercolor="$background" --insidewrongcolor="$error" --ringvercolor="$foreground" \
       --ringwrongcolor="$foreground" --separatorcolor="$error" --verifcolor="$foreground" \
       --wrongcolor="$foreground" --timecolor="$foreground" --datecolor="$highlight" \
       --datestr="%A, %d/%m/%y"

pkill -u "$USER" -USR2 dunst
