#!/usr/bin/env fish

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; sleep 1; end

set -l lines (polybar -m | sed -e 's/:.*$//g')
for mon in $lines
  set -x MONITOR $mon
  set -x CHECKUPDATES_DB (mktemp -d)
  switch $hostname
    case 'toad'
      set -x MODULES_LEFT 'slope2 slope4 arch slope2 bsp'
      set -x MODULES_RIGHT 'gmail updates available-space wlan volume battery slope3 powermenu slope1 slope3'
      polybar bottombar &
    case 'peach'
      set -x MODULES_LEFT 'padding bsp'
      set -x MODULES_RIGHT 'gmail updates available-space vpn eth wlan volume battery padding'
    case 'bowser'
      set -x MODULES_LEFT 'padding bsp'
      set -x MODULES_RIGHT 'gmail updates available-space eth volume battery padding'
  end
  polybar topbar &
end
