#!/usr/bin/env fish

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u (id -u) -x polybar >/dev/null; usleep 100; end

set -l lines (polybar -m | sed -e 's/:.*$//g')
for mon in $lines
  set -x MONITOR $mon
  set -x CHECKUPDATES_DB (mktemp -d)
  switch $hostname
    case 'toad'
      set -x MODULES_LEFT 'slope2 slope4 arch slope2 bsp'
      set -x MODULES_RIGHT 'updates gmail available-space wlan dunst volume battery slope3 powermenu slope1 slope3'
      polybar bottombar &
    case 'peach'
      set -x MODULES_LEFT 'padding bsp'
      set -x MODULES_RIGHT 'updates gmail available-space vpn eth wlan dunst volume battery padding'
    case 'bowser'
      set -x MODULES_LEFT 'padding bsp'
      set -x MODULES_RIGHT 'updates gmail available-space eth dunst volume battery padding'
    case 'ray'
      set -x MODULES_LEFT 'padding bsp'
      set -x MODULES_RIGHT 'updates gmail available-space available-space-data eth dunst volume padding'
  end
  polybar topbar &
end
